feat: adding ngrok ingress controller
canonical/microk8s-community-addons pull request #213
Opened 2023-12-01 17:41 UTC by russorat

### Thank you for making MicroK8s better

Please reference the issue this PR is fixing, or provide a description of the problem addressed.

*Also verify you have:*
* [ ] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [ ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.

2023-12-05 07:59 UTC, neoaggelos requested changes
Thanks @russorat, the changes look fine to me, left some minor comments!

For the CLA check, please amend the commits to use the email of your launchpad account, otherwise it will probably keep failing.

2023-12-05 07:59 UTC, neoaggelos commented on addons.yaml
> +        - amd64
Please add a final new-line, that should make prettier happy

2023-12-05 07:59 UTC, neoaggelos commented on addons/ngrok/disable
Needs `chmod +x ./addons/ngrok/disable`, because of this error

```
disable hook for ngrok addon needs execute permissions
```

2023-12-05 09:01 UTC, russorat commented
thanks! fixed the comments and rewrote with my ngrok email as the author.

2023-12-11 18:15 UTC, russorat commented
i think i finally got the test working. thank you!

2023-12-12 06:46 UTC, ktsakalozos commented
Hi @russorat thank you for this PR. Apart from the failing test, we would also like to see that the addon deploys a specific released version and not the latest. What we put on the main HEAD will be put in the next MicroK8s release and therefore:
- we need to make sure the tests do not break in the future and not block the patch releases
- provide the same UX throughout time

2023-12-12 07:27 UTC, russorat commented
sounds good. i've added a specific version and i think i've fixed the test.

2023-12-12 23:37 UTC, russorat commented
seems like the latest test failure isn't related to my ngrok code, but maybe i'm missing something?

2023-12-13 08:33 UTC, merged